{% if true %}
  <div class="widget-wrap">
    <h3 class="widget-title">Weibo Show</h3>
    <div class="widget-weibo">
      <iframe width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="//widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=1&speed=0&skin=5&isTitle=1&noborder=1&isWeibo=1&isFans=1&uid=5143642701&verifier=c044f752&dpc=1"></iframe>
    </div>
  </div>
{% endif %}
